### ISSUE TITLE
additional templates

### ISSUE THREAD

**Issue by heapwolf** [socketsupply/create-socket-app#1]
I added the first vanilla template but we should create extremely minimal templates for popular frontends (https://github.com/socketsupply/create-socket-app/tree/main/templates). The following are needed, also perhaps an invitation from front-end framework authors to create new ones.

- [x] react
- [x] vue
- [x] svelt
- [x] tonic
- [ ] next

**Comment by chicoxyzzy** [comment]
All except `next` has been added now. I think that we don't Next example, since Socket apps don't need server, routing, SSR, etc.

**Comment by chicoxyzzy** [comment]
also I have a wip local branch with vite integration
https://github.com/socketsupply/create-socket-app/issues/7
