### ISSUE TITLE
PowerShell keeps closing every time I run `iwr -useb https://sockets.sh/ps | iex` 

### ISSUE THREAD

**Issue by lamiazar** [socketsupply/create-socket-app#26]
This command worked the first time, but after that every time I try to run it, the PowerShell window closes.

**Comment by mribbons** [comment]
This is resolved in https://github.com/socketsupply/sockets.sh main.
@heapwolf Can you push master to the webs please.

**Comment by heapwolf** [comment]
Deployed.

**Comment by mribbons** [comment]
Should be good now @lamiazar!

**Comment by lamiazar** [comment]
> Should be good now @lamiazar!
 I just tested it, and yes it's all good.

**Comment by lamiazar** [comment]
Thank you @mribbons
