### ISSUE TITLE
Revise create-socket-app so it is has access to stdio: 'inherit'

### ISSUE THREAD

**Issue by Dotnaught** [socketsupply/create-socket-app#32]
This is a [suggestion](https://github.com/SocketDev/socket-cli-js/issues/32#issuecomment-1476336685) to resolve a problem when trying to build a Socket Runtime app while Socket.dev's similarly named security tool is active.

See [this issue](https://github.com/SocketDev/socket-cli-js/issues/32) for details.

**Comment by mribbons** [comment]
Fixed as of https://github.com/socketsupply/create-socket-app/tree/v1.0.16
