### ISSUE TITLE
why it ask elevated permissions?

### ISSUE THREAD

**Issue by lu-zen** [socketsupply/create-socket-app#36]
```
Initializing npm package...Ok.
Installing developer dependencies...Ok.
Installing '@socketsupply/socket' locally (ssc not in PATH)
Installing dependencies...
Ok.
Adding package scripts...Ok.
Creating socket files...
> socket-supply@1.0.0 init-project
> ssc init

[sudo] password for user: 
```

**Comment by mribbons** [comment]
Hi @lu-zen,
Are you on linux?

`ssc` requires some apt packages to run and build, you can review https://github.com/socketsupply/socket/blob/master/bin/install.sh to see what will be installed.

There's a change pending for the next package that will inform you what `sudo` command is running.

**Comment by lu-zen** [comment]
Yes I'm on linux, will be great to put prompts about whats going on in the background. 
thanks
