### ISSUE TITLE
`npm test`

### ISSUE THREAD

**Issue by nichoth** [socketsupply/create-socket-app#39]
The command `npm test` hangs indefinitely. This is after `npx create-socket-app tonic`.

<img width="682" alt="image" src="https://github.com/socketsupply/create-socket-app/assets/5776508/8cd5e55b-a61e-4b50-a707-4f15a11ab89f">

**Comment by lamiazar** [comment]
I was able to reproduce this issue, `npx create-socket-app tonic` works but then it hangs when running `npm test`.

**Comment by nichoth** [comment]
This is relevant in current version of `ssc` when installed locally.

```js
  "dependencies": {
    "@socketsupply/socket": "^0.3.3",
```

The tests do work if I use the globally installed `ssc` version, which is `0.3.0 (20f3364d)`

**Comment by lamiazar** [comment]
@nichoth I tested the `npm start` command, the process doesn't hang like before and also it opens the app
![Uploading Screenshot 2023-06-26 at 8.32.38 AM.png…]()

**Comment by lamiazar** [comment]
@nichoth please reopen it if you are experiencing any issues.
