### ISSUE TITLE
MacOS Monterey has libuv error

### ISSUE THREAD

**Issue by sheldonth** [socketsupply/create-socket-app#45]
When I run ssc build -r I see lots of 

node/v16.13.0/lib/node_modules/@socketsupply/socket/node_modules/@socketsupply/socket-darwin-arm64/lib/arm64-desktop/libuv.a(libuv_la-tcp.o)) was built for newer macOS version (13.0) than being linked (12.0)

I can just upgrade MacOS I suppose - but wanted to throw this out there in case you felt like offering a version linked to an older version of libuv. 

The build also fails with some missing symbols.

**Comment by lamiazar** [comment]
> I can just upgrade MacOS I suppose - but wanted to throw this out there in case you felt like offering a version linked to an older version of libuv.

@sheldonth Thank you for reporting this issue. Currently, our main focus is building for newer macOS versions, supporting older versions is not our priority at the moment.
If you have any additional questions, please lets us know.
