### ISSUE TITLE
Unable to copy files: Error: EEXIST: file already exists

### ISSUE THREAD

**Issue by lucasreppewelander** [socketsupply/create-socket-app#50]
Getting this issue when trying to do `npx create-socket-app react-ts`

```
Copying project boilerplate...
Unable to copy files: Error: EEXIST: file already exists, mkdir '..my/path/to/my/project/src'
```

so at the moment i am unable to use create-socket-app.

I'm running macOS Ventura 13.5 (22G74) and i tried both through iterm2 and via the built-in terminal

**Comment by lucasreppewelander** [comment]
<img width="798" alt="Screenshot 2023-09-13 at 15 17 24" src="https://github.com/socketsupply/create-socket-app/assets/22000298/8ec18abe-c6d6-491e-b954-e7c3f1a97845">

It still breaks..

**Comment by chicoxyzzy** [comment]
I can't reproduce. Please try to update the lates `create-socket-app` and `ssc` v0.4.0

**Comment by lucasreppewelander** [comment]
```
ssc -v
0.4.0 (6409910e)
```
i just installed everything this morning when i heard about something different to electron :)

**Comment by jwerle** [comment]
hi @lucasreppewelander which version of `node` are you running?

**Comment by lucasreppewelander** [comment]
<img width="258" alt="Screenshot 2023-09-13 at 17 48 19" src="https://github.com/socketsupply/create-socket-app/assets/22000298/59a09a5e-47ab-42dd-9f98-c074fc0bca52">

which versions are you on? as im using NVM so i can easily switch :)

**Comment by chicoxyzzy** [comment]
What's the output of `npm ls -g create-socket-app --depth 0`?

**Comment by lucasreppewelander** [comment]
<img width="745" alt="Screenshot 2023-09-13 at 17 57 16" src="https://github.com/socketsupply/create-socket-app/assets/22000298/dba046d9-7a23-4b21-8ea6-5697d9e96148">

it says empty tho

**Comment by lucasreppewelander** [comment]
`1.0.17` worked!

<img width="621" alt="Screenshot 2023-09-13 at 18 23 11" src="https://github.com/socketsupply/create-socket-app/assets/22000298/f960b669-405f-49d9-902a-bcddf9685bd6">
